### ISSUE TITLE
Mein Issue für Robert

### ISSUE THREAD

**Issue by dpaiha** [carstenscharlemann/Climb-Obc-Sandbox#10]
Swarat wegnam Tästn ;-)

**Comment by RobertK66** [comment]
Hi @dpaiha ,
welcome to our github :wink:

Makst an bulrikwest?

**Comment by RobertK66** [comment]
... Hab' inzwischen den hier geschafft anzulegen bei Dir:  https://github.com/dpaiha/test/pull/2 

Scheint so zu funken, wie ich gedacht hab'. Im Fork mach ich was ich will und zu Dir kommt die Änderung als Pull Request....

**Comment by dpaiha** [comment]
Ich sah es (nach dem Mittagessen)

________________________________
